name: ci
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.8.0

      - name: Test
        run: make test
  
  rustfmt:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v5

        - name: Rust Cache
          uses: Swatinem/rust-cache@v2.8.0

        - name: Rust rustfmt
          run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Rust cache
        uses: Swatinem/rust-cache@v2.8.0

      - name: Run cargo check
        run: RUSTFLAGS="-Dwarnings" cargo check

      - name: Run clippy
        run: cargo clippy